# Buscar Dados de Ordem de Serviços do MySQL

Este notebook conecta ao banco MySQL, executa um JOIN entre tabelas e exporta os dados para CSV.

## 1. Importar Bibliotecas

In [15]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

## 2. Configurar Credenciais do Banco de Dados

In [16]:
# Configure suas credenciais aqui
config = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',  # Altere com seu usuário
    'password': '123456',  # Altere com sua senha
    'database': 'grotrack'  # Altere com o nome do seu banco
}

## 3. Conectar ao Banco de Dados

In [17]:
def conectar_mysql(config):
    """Conecta ao banco de dados MySQL"""
    try:
        conexao = mysql.connector.connect(**config)
        
        if conexao.is_connected():
            print("✓ Conexão estabelecida com sucesso!")
            return conexao
    
    except Error as erro:
        print(f"✗ Erro ao conectar ao MySQL: {erro}")
        return None

# Estabelecer conexão
conexao = conectar_mysql(config)

✓ Conexão estabelecida com sucesso!

## 4. Executar Query no Banco de Dados

In [18]:
def buscar_dados(conexao):
    """Executa a query e retorna os dados"""
    try:
        cursor = conexao.cursor(dictionary=True)
        
        query = """
        SELECT * FROM ordem_de_servicos os 
        JOIN itens_servicos s ON s.fk_ordem_servico = os.id_ordem_servico;
        """
        
        cursor.execute(query)
        dados = cursor.fetchall()
        cursor.close()
        
        print(f"✓ {len(dados)} registros recuperados")
        return dados
    
    except Error as erro:
        print(f"✗ Erro ao executar query: {erro}")
        return None

# Executar query
if conexao:
    dados = buscar_dados(conexao)

✓ 45 registros recuperados

## 5. Converter para DataFrame

In [19]:
# Converter para DataFrame
if dados:
    df = pd.DataFrame(dados)
    print(f"\n✓ DataFrame criado com {len(df)} linhas e {len(df.columns)} colunas")
    print(f"\nColunas: {list(df.columns)}")
else:
    print("✗ Nenhum dado para converter")
    df = None

✓ DataFrame criado com 45 linhas e 21 colunas

Colunas: ['id_ordem_servico', 'valor_total', 'valor_total_servicos', 'valor_total_produtos', 'data_saida_prevista', 'data_saida_efetiva', 'data_atualizacao', 'status', 'seguradora', 'nf_realizada', 'pagt_realizado', 'ativo', 'id_registro_servico', 'fk_ordem_servico', 'preco_cobrado', 'parte_veiculo', 'lado_veiculo', 'tipo_servico', 'cor', 'especificacao_servico', 'tipo_pintura']

## 6. Visualizar Dados

In [20]:
# Visualizar primeiras linhas
if df is not None:
    display(df.head())

,id_ordem_servico,valor_total,valor_total_servicos,valor_total_produtos,data_saida_prevista,data_saida_efetiva,data_atualizacao,status,seguradora,nf_realizada,...,ativo,id_registro_servico,fk_ordem_servico,preco_cobrado,parte_veiculo,lado_veiculo,tipo_servico,cor,especificacao_servico,tipo_pintura
0,4,780.0,780.0,0.0,2026-03-28,None,2026-05-13,CANCELADO,1,0,...,0,90,4,780.0,PARACHOQUE,DIANTEIRO,FUNILARIA,Branco,Recuperação de parachoque dianteiro com alinha...,NAO_APLICAVEL
1,5,2989.9,1940.0,1049.9,2026-03-27,None,2026-05-11,EM_PRODUCAO,0,0,...,1,91,5,1250.0,PORTA,TRASEIRO_DIREITO,PINTURA,Prata,Pintura parcial em porta traseira direita após...,PARCIAL
2,5,2989.9,1940.0,1049.9,2026-03-27,None,2026-05-11,EM_PRODUCAO,0,0,...,1,92,5,690.0,CAIXA_DE_RODA,TRASEIRO_ESQUERDO,FUNILARIA,Prata,Funilaria em caixa de roda traseira esquerda,NAO_APLICAVEL
3,6,2079.6,1400.0,679.6,2026-03-20,2026-03-21,2026-05-11,FINALIZADO,1,1,...,1,93,6,840.0,CURVAO,DIANTEIRO_ESQUERDO,PINTURA,Azul,Pintura parcial na coluna frontal esquerda,PARCIAL
4,6,2079.6,1400.0,679.6,2026-03-20,2026-03-21,2026-05-11,FINALIZADO,1,1,...,1,94,6,560.0,PAINEL,COMPLETO,MECANICA,NaN,Revisão e ajuste de painel elétrico interno,NAO_APLICAVEL

## 7. Informações do DataFrame

In [21]:
# Informações sobre o DataFrame
if df is not None:
    print(df.info())
    print("\nEstatísticas:")
    display(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_ordem_servico       45 non-null     int64
 1   valor_total            45 non-null     float64
 2   valor_total_servicos   45 non-null     float64
 3   valor_total_produtos   45 non-null     float64
 4   data_saida_prevista    45 non-null     object
 5   data_saida_efetiva     19 non-null     object
 6   data_atualizacao       45 non-null     object
 7   status                 45 non-null     str
 8   seguradora             45 non-null     int64
 9   nf_realizada           45 non-null     int64
 10  pagt_realizado         45 non-null     int64
 11  ativo                  45 non-null     int64
 12  id_registro_servico    45 non-null     int64
 13  fk_ordem_servico       45 non-null     int64
 14  preco_cobrado          45 non-null     float64
 15  parte_veiculo          45 non-null     str
 16  lado_veiculo           45 non-null     str
 17  tipo_servico           45 non-null     str
 18  cor                    40 non-null     str
 19  especificacao_servico  45 non-null     str
 20  tipo_pintura           45 non-null     str
dtypes: float64(4), int64(7), object(3), str(7)
memory usage: 7.5+ KB
None

Estatísticas:

,id_ordem_servico,valor_total,valor_total_servicos,valor_total_produtos,seguradora,nf_realizada,pagt_realizado,ativo,id_registro_servico,fk_ordem_servico,preco_cobrado
count,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
mean,21.911111,1456.697778,1231.333333,225.364444,0.488889,0.244444,0.400000,0.955556,114.533333,21.911111,709.333333
std,10.943704,641.505415,483.592616,230.031935,0.505525,0.434613,0.495434,0.208409,13.850829,10.943704,217.844815
min,4.000000,414.000000,330.000000,0.000000,0.000000,0.000000,0.000000,0.000000,90.000000,4.000000,310.000000
25%,13.000000,988.000000,870.000000,95.000000,0.000000,0.000000,0.000000,1.000000,104.000000,13.000000,540.000000
50%,21.000000,1477.000000,1300.000000,170.800000,0.000000,0.000000,0.000000,1.000000,115.000000,21.000000,730.000000
75%,31.000000,1844.500000,1570.000000,274.500000,1.000000,0.000000,1.000000,1.000000,126.000000,31.000000,860.000000
max,40.000000,2989.900000,1960.000000,1049.900000,1.000000,1.000000,1.000000,1.000000,137.000000,40.000000,1250.000000

## 8. Exportar para CSV

In [22]:
def gerar_csv(df, nome_arquivo='servicos.csv'):
    """Exporta DataFrame para arquivo CSV"""
    try:
        df.to_csv(nome_arquivo, index=False, encoding='utf-8')
        print(f"✓ Arquivo '{nome_arquivo}' gerado com sucesso!")
        return True
    except Exception as erro:
        print(f"✗ Erro ao gerar CSV: {erro}")
        return False

# Gerar CSV
if df is not None:
    gerar_csv(df, 'servicos.csv')

✓ Arquivo 'servicos.csv' gerado com sucesso!

## 9. Fechar Conexão

In [23]:
# Fechar conexão
if conexao and conexao.is_connected():
    conexao.close()
    print("✓ Conexão fechada.")

✓ Conexão fechada.